apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-logs-app
  labels:
    app: fake-logs-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-logs-app
  template:
    metadata:
      labels:
        app: fake-logs-app
    spec:
      containers:
      - name: custom
        image: saphoooo/fake-logs-app:latest
        command: ['/fake-logs-app']
        args: ['-f', '1']
      - name: nginx
        image: saphoooo/fake-logs-app:latest
        command: ['/fake-logs-app']
        args: ['-o', 'nginx', '-f', '2']