apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-logs-team-yellow
  labels:
    app: fake-logs-team-yellow
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-logs-team-yellow
  template:
    metadata:
      labels:
        app: fake-logs-team-yellow
    spec:
      containers:
      - name: custom
        image: saphoooo/fake-logs-app:latest
        args: ['-i', '1']
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: fake-logs-team-green
  labels:
    app: fake-logs-team-green
spec:
  replicas: 1
  selector:
    matchLabels:
      app: fake-logs-team-green
  template:
    metadata:
      labels:
        app: fake-logs-team-green
    spec:
      containers:
      - name: nginx
        image: saphoooo/fake-logs-app:latest
        args: ['-f', 'nginx', '-i', '1']